/**
 * Seed data mirrored from wontech-frontend/lib/mock-data.ts (mockClinics).
 * `key` matches mock ids so parentKey can resolve branch → parent links.
 */
export type ClinicSeed = {
  key: string;
  groupName: string;
  name: string;
  addressStreet: string;
  addressCity: string;
  addressCode: string;
  contactEmail: string;
  parentKey?: string | null;
};

export const CLINIC_SEEDS: ClinicSeed[] = [
  {
    key: 'c-1',
    groupName: 'Wontech Central Clinic',
    name: 'Wontech Central Clinic',
    addressStreet: '88 Sukhumvit Soi 24',
    addressCity: 'Khlong Toei, Bangkok',
    addressCode: '10110',
    contactEmail: 'contact@wontech-central.clinic',
    parentKey: null,
  },
  {
    key: 'c-2',
    groupName: 'Siam Skin & Wellness',
    name: 'Siam Skin & Wellness',
    addressStreet: '12 Rama I Rd',
    addressCity: 'Pathum Wan, Bangkok',
    addressCode: '10330',
    contactEmail: 'contact@siamskin.clinic',
    parentKey: null,
  },
  {
    key: 'c-3',
    groupName: 'Siam Skin & Wellness',
    name: 'Siam Skin — Sukhumvit',
    addressStreet: '101 Sukhumvit Rd',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'sukhumvit@siamskin.clinic',
    parentKey: 'c-2',
  },
  {
    key: 'c-4',
    groupName: 'Siam Skin & Wellness',
    name: 'Siam Skin — Silom',
    addressStreet: '45 Silom Rd',
    addressCity: 'Bang Rak, Bangkok',
    addressCode: '10500',
    contactEmail: 'silom@siamskin.clinic',
    parentKey: 'c-2',
  },
  {
    key: 'c-5',
    groupName: 'Radiance MedSpa',
    name: 'Radiance MedSpa',
    addressStreet: '200 Phahonyothin Rd',
    addressCity: 'Chatuchak, Bangkok',
    addressCode: '10900',
    contactEmail: 'contact@radiancemedspa.clinic',
    parentKey: null,
  },
  {
    key: 'c-6',
    groupName: 'Radiance MedSpa',
    name: 'Radiance MedSpa — Ari',
    addressStreet: '8 Ari Soi 1',
    addressCity: 'Phaya Thai, Bangkok',
    addressCode: '10400',
    contactEmail: 'ari@radiancemedspa.clinic',
    parentKey: 'c-5',
  },
  {
    key: 'c-7',
    groupName: 'Glow Clinic',
    name: 'Glow Clinic',
    addressStreet: '33 Thong Lo Soi 13',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'contact@glow.clinic',
    parentKey: null,
  },
  {
    key: 'c-8',
    groupName: 'Aura Dermatology',
    name: 'Aura Dermatology',
    addressStreet: '55 Wireless Rd',
    addressCity: 'Lumphini, Bangkok',
    addressCode: '10330',
    contactEmail: 'contact@auraderm.clinic',
    parentKey: null,
  },
  {
    key: 'c-9',
    groupName: 'Lotus Aesthetic Studio',
    name: 'Lotus Aesthetic Studio',
    addressStreet: '17 Ratchadamri Rd',
    addressCity: 'Pathum Wan, Bangkok',
    addressCode: '10330',
    contactEmail: 'hello@lotusaesthetic.clinic',
    parentKey: null,
  },
  {
    key: 'c-10',
    groupName: 'Serene Skin Bangkok',
    name: 'Serene Skin Bangkok',
    addressStreet: '72 Soi Thong Lo 10',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'info@sereneskin.clinic',
    parentKey: null,
  },
  {
    key: 'c-11',
    groupName: 'Velvet Touch Clinic',
    name: 'Velvet Touch Clinic',
    addressStreet: '4 Soi Lang Suan',
    addressCity: 'Lumphini, Bangkok',
    addressCode: '10330',
    contactEmail: 'contact@velvettouch.clinic',
    parentKey: null,
  },
  {
    key: 'c-12',
    groupName: 'Harmony Face & Body',
    name: 'Harmony Face & Body',
    addressStreet: '156 Phetchaburi Rd',
    addressCity: 'Ratchathewi, Bangkok',
    addressCode: '10400',
    contactEmail: 'hello@harmonyface.clinic',
    parentKey: null,
  },
  {
    key: 'c-13',
    groupName: 'Crystal Clear MedSpa',
    name: 'Crystal Clear MedSpa',
    addressStreet: '29 Soi Ekkamai 12',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'book@crystalclear.clinic',
    parentKey: null,
  },
  {
    key: 'c-14',
    groupName: 'Bloom Beauty House',
    name: 'Bloom Beauty House',
    addressStreet: '91 Rama IX Rd',
    addressCity: 'Huai Khwang, Bangkok',
    addressCode: '10310',
    contactEmail: 'contact@bloombeauty.clinic',
    parentKey: null,
  },
  {
    key: 'c-15',
    groupName: 'Nirvana Skin Lab',
    name: 'Nirvana Skin Lab',
    addressStreet: '6 Soi Ari 4',
    addressCity: 'Phaya Thai, Bangkok',
    addressCode: '10400',
    contactEmail: 'info@nirvanaskin.clinic',
    parentKey: null,
  },
  {
    key: 'c-16',
    groupName: 'Elite Derma Center',
    name: 'Elite Derma Center',
    addressStreet: '220 Sathorn Rd',
    addressCity: 'Bang Rak, Bangkok',
    addressCode: '10500',
    contactEmail: 'hello@elitederma.clinic',
    parentKey: null,
  },
  {
    key: 'c-17',
    groupName: 'Muse Aesthetic Clinic',
    name: 'Muse Aesthetic Clinic',
    addressStreet: '14 Soi Phrom Phong 4',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'contact@museaesthetic.clinic',
    parentKey: null,
  },
  {
    key: 'c-18',
    groupName: 'Golden Hour MedSpa',
    name: 'Golden Hour MedSpa',
    addressStreet: '48 Lat Phrao Rd',
    addressCity: 'Chatuchak, Bangkok',
    addressCode: '10900',
    contactEmail: 'book@goldenhour.clinic',
    parentKey: null,
  },
  {
    key: 'c-19',
    groupName: 'Silk & Skin Bangkok',
    name: 'Silk & Skin Bangkok',
    addressStreet: '3 Soi Convent',
    addressCity: 'Silom, Bangkok',
    addressCode: '10500',
    contactEmail: 'info@silkandskin.clinic',
    parentKey: null,
  },
  {
    key: 'c-20',
    groupName: 'Opal Laser Studio',
    name: 'Opal Laser Studio',
    addressStreet: '67 Ratchadaphisek Rd',
    addressCity: 'Din Daeng, Bangkok',
    addressCode: '10400',
    contactEmail: 'contact@opallaser.clinic',
    parentKey: null,
  },
  {
    key: 'c-21',
    groupName: 'Zen Garden Wellness',
    name: 'Zen Garden Wellness',
    addressStreet: '22 Soi Ngam Duphli',
    addressCity: 'Sathon, Bangkok',
    addressCode: '10120',
    contactEmail: 'hello@zengarden.clinic',
    parentKey: null,
  },
  {
    key: 'c-22',
    groupName: 'Luxe Skin Collective',
    name: 'Luxe Skin Collective',
    addressStreet: '105 Sukhumvit Soi 55',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'info@luxeskin.clinic',
    parentKey: null,
  },
  {
    key: 'c-23',
    groupName: 'Petal Face Clinic',
    name: 'Petal Face Clinic',
    addressStreet: '18 Charoen Krung Soi 36',
    addressCity: 'Bang Rak, Bangkok',
    addressCode: '10500',
    contactEmail: 'contact@petalface.clinic',
    parentKey: null,
  },
  {
    key: 'c-24',
    groupName: 'Summit Aesthetics',
    name: 'Summit Aesthetics',
    addressStreet: '40 Vibhavadi Rangsit Rd',
    addressCity: 'Chatuchak, Bangkok',
    addressCode: '10900',
    contactEmail: 'book@summitaesthetics.clinic',
    parentKey: null,
  },
  {
    key: 'c-25',
    groupName: 'Coral Reef MedSpa',
    name: 'Coral Reef MedSpa',
    addressStreet: '9 Soi Asok 3',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'hello@coralreef.clinic',
    parentKey: null,
  },
  {
    key: 'c-26',
    groupName: 'Luminous Aesthetics',
    name: 'Luminous Aesthetics',
    addressStreet: '50 Rama IV Rd',
    addressCity: 'Silom, Bangkok',
    addressCode: '10500',
    contactEmail: 'contact@luminous.clinic',
    parentKey: null,
  },
  {
    key: 'c-27',
    groupName: 'Luminous Aesthetics',
    name: 'Luminous — Ekkamai',
    addressStreet: '25 Soi Ekkamai 5',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'ekkamai@luminous.clinic',
    parentKey: 'c-26',
  },
  {
    key: 'c-28',
    groupName: 'Luminous Aesthetics',
    name: 'Luminous — On Nut',
    addressStreet: '112 Sukhumvit Soi 77',
    addressCity: 'Phra Khanong, Bangkok',
    addressCode: '10250',
    contactEmail: 'onnut@luminous.clinic',
    parentKey: 'c-26',
  },
  {
    key: 'c-29',
    groupName: 'Bella Dermatology',
    name: 'Bella Dermatology',
    addressStreet: '7 North Sathorn Rd',
    addressCity: 'Bang Rak, Bangkok',
    addressCode: '10500',
    contactEmail: 'contact@belladerm.clinic',
    parentKey: null,
  },
  {
    key: 'c-30',
    groupName: 'Bella Dermatology',
    name: 'Bella — Sathorn',
    addressStreet: '88 Naradhiwas Rajanagarindra Rd',
    addressCity: 'Sathon, Bangkok',
    addressCode: '10120',
    contactEmail: 'sathorn@belladerm.clinic',
    parentKey: 'c-29',
  },
  {
    key: 'c-31',
    groupName: 'Pure Harmony Spa',
    name: 'Pure Harmony Spa',
    addressStreet: '130 Ratchaprarop Rd',
    addressCity: 'Ratchathewi, Bangkok',
    addressCode: '10400',
    contactEmail: 'contact@pureharmony.clinic',
    parentKey: null,
  },
  {
    key: 'c-32',
    groupName: 'Pure Harmony Spa',
    name: 'Pure Harmony — Phrom Phong',
    addressStreet: '42 Sukhumvit Soi 39',
    addressCity: 'Watthana, Bangkok',
    addressCode: '10110',
    contactEmail: 'phromphong@pureharmony.clinic',
    parentKey: 'c-31',
  },
  {
    key: 'c-33',
    groupName: 'Pure Harmony Spa',
    name: 'Pure Harmony — Ladprao',
    addressStreet: '201 Ladprao Rd',
    addressCity: 'Chatuchak, Bangkok',
    addressCode: '10900',
    contactEmail: 'ladprao@pureharmony.clinic',
    parentKey: 'c-31',
  },
  {
    key: 'c-34',
    groupName: 'Ivory Laser Clinic',
    name: 'Ivory Laser Clinic',
    addressStreet: '63 Soi Saladaeng 1',
    addressCity: 'Silom, Bangkok',
    addressCode: '10500',
    contactEmail: 'book@ivorylaser.clinic',
    parentKey: null,
  },
  {
    key: 'c-35',
    groupName: 'Zenith Wellness',
    name: 'Zenith Wellness',
    addressStreet: '15 Soi Ploenchit 2',
    addressCity: 'Lumphini, Bangkok',
    addressCode: '10330',
    contactEmail: 'info@zenithwellness.clinic',
    parentKey: null,
  },
  {
    key: 'c-36',
    groupName: 'Orchard Beauty Lab',
    name: 'Orchard Beauty Lab',
    addressStreet: '77 Soi Sukhumvit 24',
    addressCity: 'Khlong Toei, Bangkok',
    addressCode: '10110',
    contactEmail: 'hello@orchardbeauty.clinic',
    parentKey: null,
  },
  {
    key: 'c-37',
    groupName: 'Pearl Skin Studio',
    name: 'Pearl Skin Studio',
    addressStreet: '31 Soi Phahonyothin 7',
    addressCity: 'Phaya Thai, Bangkok',
    addressCode: '10400',
    contactEmail: 'contact@pearlskin.clinic',
    parentKey: null,
  },
];
